name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
  FETCH_DEPTH: --depth=1

jobs:
  cache-dependencies:
    name: "Cache Dependencies"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/branch-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up environment
        run: mkdir -p $GRADLE_USER_HOME
      
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.GRADLE_USER_HOME }}/caches
            ${{ env.GRADLE_USER_HOME }}/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      
      - name: Run caching script
        run: bash .travis/travis-cache-dependencies.sh

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Run build script
        run: bash .travis/travis-build.sh

  junit:
    name: "JUnit Tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Run JUnit tests
        run: bash .travis/travis-junit.sh

  sonarqube-analysis:
    name: "SonarQube Analysis"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref != 'refs/heads/public_master'
    env:
      SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Run SonarQube Analysis
        run: bash .travis/travis-sq-analysis.sh


